name: Deploy to Server

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-lates

        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
              
        - name: Copy files to the server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            source: "."
            target: "/home/admin/app/transportanimal"

        - name: Deploy application
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
                cd /home/admin/app/transportanimal
                docker stop IAA || true
                docker rm IAA || true
                docker rmi transportanimal || true
                docker build -t transportanimal .
                docker run -d -p 80:80 --name IAA transportanimal
